version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 30s

  config-server:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    container_name: config-server
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 5s
      retries: 10
      start_period: 30s
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PW=${GIT_PW}

  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eureka-server

    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network

  gateway-server:
    build:
      context: ./gatewayserver
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      - eureka-server
    networks:
      - app-network

  jobbotdari:
    build:
      context: ./jobbotdari
      dockerfile: Dockerfile
    container_name: jobbotdari
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

  jobbotdari-user:
    build:
      context: ./jobbotdari_user
      dockerfile: Dockerfile
    container_name: jobbotdari-user
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    volumes:
      - jobbotdari-user-uploads:/app/uploads

  frontend:
    image: jihoonyc/frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway-server
    networks:
      - app-network
    command: [ "npm", "run", "dev", "--", "--host" ]

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  jobbotdari-user-uploads:

