version: '3.8'

services:
  mysql:
    image: jihoonyc/mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 30s

  config-server:
    image: jihoonyc/configserver:latest
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 5s
      retries: 10
      start_period: 30s

  eureka-server:
    image: jihoonyc/eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network

  gateway-server:
    image: jihoonyc/gatewayserver:latest
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      - eureka-server
    networks:
      - app-network

  jobbotdari:
    image: jihoonyc/jobbotdari:latest
    container_name: jobbotdari
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari
      - SPRING_PROFILES_ACTIVE=default

  jobbotdari-user:
    image: jihoonyc/jobbotdari_user:latest
    container_name: jobbotdari-user
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network
    volumes:
      - jobbotdari-user-uploads:/app/uploads

  frontend:
    image: jihoonyc/frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  jobbotdari-user-uploads: