# 250329 11:39 update
version: '3.8'

services:
  config-server:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: config-server
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 5s
      retries: 10
      start_period: 30s
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PW=${GIT_PW}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network


  gateway-server:
    build:
      context: ./gatewayserver
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  jobbotdari:
    build:
      context: ./jobbotdari
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: jobbotdari
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST_COMPANY}:3306/${MYSQL_DATABASE_COMPANY}?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  jobbotdari-user:
    build:
      context: ./jobbotdari_user
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: jobbotdari-user
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari-user
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST_USER}:3306/${MYSQL_DATABASE_USER}?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - jobbotdari-user-uploads:/app/uploads

  frontend:
    image: honey0928/frontend:latest
    platform: linux/amd64
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway-server
    networks:
      - app-network
    command: [ "npm", "run", "dev", "--", "--host" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jobbotdari-user-uploads:
