version: '3.8'

services:
  config-server:
    image: honey0928/configserver:latest
    platform: linux/amd64
    container_name: config-server
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 5s
      retries: 10
      start_period: 30s
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PW=${GIT_PW}

  eureka-server:
    image: honey0928/eurekaserver:latest
    platform: linux/amd64
    container_name: eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - app-network

  gateway-server:
    image: honey0928/gatewayserver:latest
    platform: linux/amd64
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      - eureka-server
    networks:
      - app-network

  jobbotdari:
    image: honey0928/jobbotdari:latest
    platform: linux/amd64
    container_name: jobbotdari
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST_COMPANY}:3306/${MYSQL_DATABASE_COMPANY}?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

  jobbotdari-user:
    image: honey0928/jobbotdari_user:latest
    platform: linux/amd64
    container_name: jobbotdari-user
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=jobbotdari-user
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST_USER}:3306/${MYSQL_DATABASE_USER}?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - jobbotdari-user-uploads:/app/uploads

  frontend:
    image: jihoonyc/frontend:latest
    platform: linux/amd64
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway-server
    networks:
      - app-network
    command: [ "npm", "run", "dev", "--", "--host" ]

networks:
  app-network:
    driver: bridge

volumes:
  jobbotdari-user-uploads:
