spring:
  application:
    name: jobbotdari

  datasource:
    url: jdbc:mysql://localhost:3306/news_db?serverTimezone=UTC
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update      # 애플리케이션 실행 시 엔티티 변경 사항에 따라 테이블을 업데이트함
    show-sql: true          # 실행되는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true   # 출력되는 SQL 쿼리를 포맷팅하여 가독성 향상

  # 스프링 시큐리티 기본 로그인 창 비활성화 (개발 중에는 필요없다고 판단)
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Groq API 설정
groq:
  api-url: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.2-90b-vision-preview
  temperature: 0.7
  api-key: API_KEY    # 실제 API키 입력