name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check environment variables
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}"
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}"
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}"
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}"

      - name: Build and Push Application Images
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PW: ${{ secrets.GIT_PW }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}"
        run: |
          SERVICES=("configserver" "eurekaserver" "gatewayserver" "jobbotdari" "jobbotdari_user")

          for SERVICE in "${SERVICES[@]}"
          do
            IMAGE_NAME="$DOCKER_HUB_USERNAME/$SERVICE"
            IMAGE_TAG="latest"
            CONTEXT="./$SERVICE"
            DOCKERFILE="$CONTEXT/Dockerfile"

            echo "Building and pushing $IMAGE_NAME:$IMAGE_TAG"

            docker build --build-arg GIT_USERNAME=$GIT_USERNAME \
                         --build-arg GIT_PW=$GIT_PW \
                         --build-arg MYSQL_DATABASE=$MYSQL_DATABASE \
                         --build-arg MYSQL_USER=$MYSQL_USER \
                         --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD \
                         --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                         --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                         --build-arg AWS_REGION=$AWS_REGION \
                         --build-arg AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME \
                         -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE $CONTEXT

            docker push $IMAGE_NAME:$IMAGE_TAG
          done
